jwtToken=egov_secret_123
spring.application.name=bid-api
server.port=7000
spring.data.mongodb.uri=mongodb://103.75.182.242:30001/winitech?retryWrites=true&w=majority&appName=Cluster0
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

img-size-limit=3145728
stream-chunk-file-rate-limit=8192

root.file.store=store
root.file.name=/store
root.folder=/bid-api

chrome-driver=/usr/lib/chromium/chromedriver
server.ssl.key-store=classpath:outbound-config/keystore.p12
server.ssl.key-store-password=1
server.ssl.key-store-type=PKCS12
server.ssl.enabled=true

server.tomcat.threads.max=400
server.tomcat.threads.min-spare=10
main-email=gavip13051995@gmail.com

email-host=imap.gmail.com
email-port=993
email-address=tomt42531@gmail.com
email-password=agjb jhvt bpzt eats

bid-email-address=Stjtrading2022@gmail.com
bid-email-password=Tungduong2024

#chrome-driver=D:/lib/chromedriver-win64/chromedriver.exe
#server.ssl.key-store=D:/Project/parttime/bid-api/jks.jks
#server.ssl.key-store-password=#*.winitech.com@
#server.ssl.key-store-type=JKS
#server.ssl.enabled=true
